### ISSUE TITLE
Can't install on node 0.12.x

### ISSUE THREAD

**Issue by huynhphan89** [dgurkaynak/nodeshout#1]

**Comment by daslicht** [comment]
a little bit more information would be helpful ?!

**Comment by dgurkaynak** [comment]
Hey guys, sorry for late response. I'm quite too busy for maintaining this repo, it was just a hobby project.
Anyway, this issue must be fixed with https://github.com/dgurkaynak/nodeshout/commit/b0ca2906621dd426ca1510396f533c47b0ac602e. I've tried with both node `v0.12.7` and `v4.2.1`. I've released version `0.0.3`. Please try to update nodeshout over npm.
